matiere({
  id: "svt", nom: "SVT", couleur: "#5E8F1C", icone: "🌱",
  chapitres: [
    {
      id: "sv-climat",
      titre: "Phénomènes climatiques et météorologiques",
      resume: "Ne pas confondre climatologie et météorologie. Les trois zones climatiques et l'énergie du Soleil.",
      savaisTu: [
        "Le climat se calcule sur une période de référence de 30 ans.",
        "« Le climat, c'est ce qu'on attend ; la météo, c'est ce qu'on a. »",
        "1 mm de précipitations, c'est 1 litre d'eau tombé sur chaque mètre carré.",
        "Le mot « météorologie » vient du grec meteoros, qui veut dire « élevé dans les airs ». Les Grecs appelaient météores tous les phénomènes du ciel, y compris les étoiles filantes : c'est le même mot qui a donné météorite.",
        "Il fait plus chaud à l'équateur non pas parce qu'on y est plus près du Soleil, mais parce que ses rayons y arrivent presque droits. Aux pôles, ils arrivent inclinés et la même quantité d'énergie s'étale sur une surface bien plus grande.",
        "Les normales de saison ne sont pas des prévisions : ce sont des moyennes calculées sur trente ans. Dire qu'un mois est « au-dessus des normales » ne dit rien du climat, seulement de ce mois-là."
      ],
      supports: [
        { id: "sv-meteo1", titre: "Météo : prévoir le temps de demain", source: "C'est pas sorcier", type: "video", lien: "https://www.youtube.com/watch?v=V1sVOEq51_o", etiquette: "decouvrir", duree: "26 min" },
        { id: "sv-meteo2", titre: "Comment prédire la météo ?", source: "C'est pas sorcier", type: "video", lien: "https://www.youtube.com/watch?v=RjWvJCDPW1I", etiquette: "consolider", duree: "26 min", note: "Le bulletin météo, c'est le document 2 de l'activité sur Lisa et le tournoi de tennis." },
        { id: "sv-climat", titre: "Le climat : son histoire et ses changements", source: "C'est pas sorcier", type: "video", lien: "https://www.youtube.com/watch?v=lShBAXMb2yU", etiquette: "plusloin", duree: "26 min" }
      ],
      quiz: [
        { q: "« Demain, il pleuvra sur Paris. » C'est…", options: ["de la météo", "du climat"], bonne: 0, explication: "Une prévision à court terme, sur une zone limitée : c'est de la météorologie.", point: "Trier météo et climat", revoir: "sv-meteo1", fixe: true },
        { q: "« En moyenne, il fait plus chaud en été qu'en hiver à Paris. » C'est…", options: ["de la météo", "du climat"], bonne: 1, explication: "Une moyenne calculée sur de nombreuses années : c'est du climat.", point: "Trier météo et climat", revoir: "sv-climat", fixe: true },
        { q: "« Cette semaine, des matchs du tournoi de tennis ont été reportés à cause de la pluie. » C'est…", options: ["de la météo", "du climat"], bonne: 0, explication: "Un épisode de quelques jours : c'est un événement météorologique.", point: "Trier météo et climat", revoir: "sv-meteo2", fixe: true },
        { q: "« Le Sahara reçoit très peu de pluie, année après année. » C'est…", options: ["de la météo", "du climat"], bonne: 1, explication: "Ce qui se répète en moyenne sur des années décrit le climat.", point: "Trier météo et climat", revoir: "sv-climat", fixe: true },
        { q: "« Un orage violent a éclaté hier soir. » C'est…", options: ["de la météo", "du climat"], bonne: 0, explication: "Un phénomène ponctuel, à court terme : c'est de la météo.", point: "Trier météo et climat", revoir: "sv-meteo1", fixe: true },
        { q: "La climatologie étudie…", options: ["les valeurs moyennes des températures et des précipitations sur de nombreuses années", "le temps qu'il fera demain", "les tremblements de terre"], bonne: 0, explication: "Ces moyennes sont établies grâce à des mesures régulières pendant des années.", point: "Définir climat et météo", revoir: "sv-climat" },
        { q: "La météorologie étudie…", options: ["les phénomènes à court terme sur une zone limitée", "les moyennes sur des centaines d'années", "l'histoire de la Terre"], bonne: 0, explication: "Précipitations, température, vent : la météo prévoit les jours qui viennent.", point: "Définir climat et météo", revoir: "sv-meteo2" },
        { q: "Sur combien d'années calcule-t-on un climat de référence ?", options: ["30 ans", "1 an", "1 mois"], bonne: 0, explication: "La période de référence est de 30 ans.", point: "Définir climat et météo", revoir: "sv-climat" },
        { q: "1 mm de précipitations correspond à…", options: ["1 litre d'eau par mètre carré", "1 goutte par mètre carré", "1 seau d'eau par mètre carré"], bonne: 0, explication: "C'est la définition donnée dans le document 1.", point: "Les précipitations" },
        { q: "Un mois de mai très pluvieux prouve-t-il que le climat se dérègle ?", options: ["Non, c'est un événement météorologique", "Oui, forcément"], bonne: 0, explication: "Pour parler de climat, il faut comparer des moyennes sur de nombreuses années, pas un seul mois.", point: "Trier météo et climat", revoir: "sv-meteo2" },
        { q: "Pourquoi existe-t-il plusieurs zones climatiques sur Terre ?", options: ["Parce que le rayonnement du Soleil est inégalement réparti", "Parce que certains pays sont plus près du Soleil", "Parce que les océans chauffent l'air"], bonne: 0, explication: "Près de l'équateur, les rayons arrivent presque droits ; près des pôles, ils arrivent inclinés et se répartissent sur une plus grande surface.", point: "Les zones climatiques", revoir: "sv-climat" },
        { q: "Quel est le mot exact pour l'étude des moyennes sur une longue durée ?", options: ["la climatologie", "la météorologie", "la géologie"], bonne: 0, explication: "Climatologie : conditions moyennes (températures, précipitations) sur une région donnée, pendant plusieurs décennies.", point: "Le lexique du chapitre", revoir: "sv-climat", fixe: true },
        { q: "Et pour l'étude du temps à court terme, sur une zone limitée ?", options: ["la météorologie", "la climatologie", "l'astronomie"], bonne: 0, explication: "C'est la définition du lexique, mot pour mot.", point: "Le lexique du chapitre", revoir: "sv-meteo1", fixe: true },
        { q: "Combien y a-t-il de grandes zones climatiques sur Terre ?", options: ["Trois", "Deux", "Cinq"], bonne: 0, explication: "Trois : la zone chaude, la zone tempérée et la zone froide, qu'on appelle aussi polaire.", point: "Les zones climatiques", revoir: "sv-climat", fixe: true },
        { q: "Comment ces trois zones sont-elles disposées ?", options: ["De part et d'autre de l'équateur", "Du nord au sud, en bandes verticales", "Au hasard"], bonne: 0, explication: "La carte du document 1 le montre : la zone chaude autour de l'équateur, puis les zones tempérées, puis les zones froides vers les pôles.", point: "Les zones climatiques", revoir: "sv-climat" },
        { q: "Qu'est-ce qui explique l'existence de ces zones ?", options: ["L'inégale répartition de l'énergie solaire à la surface de la Terre", "La distance entre chaque pays et le Soleil", "La profondeur des océans"], bonne: 0, explication: "C'est ce que démontre le modèle expérimental : l'énergie solaire est plus concentrée à l'équateur qu'aux pôles.", point: "Les zones climatiques", revoir: "sv-climat", fixe: true },
        { q: "En zone tempérée, les relevés donnent 9,7 °C et 767 mm par an. En climat équatorial…", options: ["23,8 °C et 1617 mm par an", "5 °C et 200 mm par an", "les mêmes valeurs"], bonne: 0, explication: "Températures et précipitations sont bien plus élevées en zone chaude : ce sont les chiffres des graphiques de l'activité.", point: "Lire les graphiques", revoir: "sv-climat" },
        { q: "Sur quelles deux mesures repose la définition d'un climat ?", options: ["Les températures et les précipitations", "Le vent et les nuages", "L'humidité et la pression"], bonne: 0, explication: "Températures et précipitations moyennes, sur une longue période et une grande zone.", point: "Le lexique du chapitre", fixe: true },
        { q: "Le grand-père de Lisa pense qu'il va pleuvoir parce qu'il a plu l'an dernier. A-t-il raison ?", options: ["Non : un épisode de pluie ne dit rien de l'année suivante", "Oui : la pluie revient toujours à la même date"], bonne: 0, explication: "C'est la conclusion de l'activité : on ne déduit rien d'un seul phénomène météorologique.", point: "Le raisonnement de l'activité", revoir: "sv-meteo2", fixe: true },
        { q: "Le graphique du document 4 montre que les précipitations…", options: ["varient d'une année à l'autre, parfois au-dessus des normales, parfois en dessous", "augmentent chaque année sans exception", "sont identiques tous les ans"], bonne: 0, explication: "Plus fortes en 2007 et 2013, plus faibles en 2011 et 2015 : cette variation est normale.", point: "Le raisonnement de l'activité", revoir: "sv-meteo2" },
        { q: "Quand peut-on parler d'un dérèglement climatique ?", options: ["Quand un phénomène se répète sur plusieurs zones et sur plusieurs années", "Dès qu'un mois est plus pluvieux que d'habitude", "Quand un orage est très violent"], bonne: 0, explication: "C'est la phrase de conclusion du cours : un seul phénomène ne suffit jamais.", point: "Le raisonnement de l'activité", revoir: "sv-climat", fixe: true },
        { q: "Quelques jours de pluie à Paris en juin 2017, c'est…", options: ["un phénomène météorologique", "une preuve de dérèglement climatique"], bonne: 0, explication: "Le document 3 sert justement à montrer le piège : quelques jours ne relèvent pas de la climatologie.", point: "Trier météo et climat", revoir: "sv-meteo2" },
        { q: "Le climat se définit sur…", options: ["une grande surface et une longue période", "une petite zone et quelques jours", "une ville et une saison"], bonne: 0, explication: "C'est l'opposition centrale du chapitre : grande surface et longue durée pour le climat, petite zone et court terme pour la météo.", point: "Définir climat et météo", fixe: true },
        { q: "Où fait-il en moyenne le plus chaud ?", options: ["Près de l'équateur", "Près des pôles"], bonne: 0, explication: "C'est là que le Soleil chauffe le plus, car ses rayons y sont concentrés sur une petite surface.", point: "Les zones climatiques", revoir: "sv-climat" }
      ]
    }
  ]
});
