matiere({
  id: "svt", nom: "SVT", couleur: "#5E8F1C", icone: "🌱",
  chapitres: [
    {
      id: "sv-climat",
      titre: "Phénomènes climatiques et météorologiques",
      resume: "Ne pas confondre climatologie et météorologie. Les trois zones climatiques et l'énergie du Soleil.",
      savaisTu: [
        "Le climat se calcule sur une période de référence de 30 ans.",
        "« Le climat, c'est ce qu'on attend ; la météo, c'est ce qu'on a. »",
        "1 mm de précipitations, c'est 1 litre d'eau tombé sur chaque mètre carré.",
        "Le mot « météorologie » vient du grec meteoros, qui veut dire « élevé dans les airs ». Les Grecs appelaient météores tous les phénomènes du ciel, y compris les étoiles filantes : c'est le même mot qui a donné météorite.",
        "Il fait plus chaud à l'équateur non pas parce qu'on y est plus près du Soleil, mais parce que ses rayons y arrivent presque droits. Aux pôles, ils arrivent inclinés et la même quantité d'énergie s'étale sur une surface bien plus grande.",
        "Les normales de saison ne sont pas des prévisions : ce sont des moyennes calculées sur trente ans. Dire qu'un mois est « au-dessus des normales » ne dit rien du climat, seulement de ce mois-là."
      ],
      supports: [
        { id: "sv-meteo1", titre: "Météo : prévoir le temps de demain", source: "C'est pas sorcier", type: "video", lien: "https://www.youtube.com/watch?v=V1sVOEq51_o", etiquette: "decouvrir", duree: "26 min" },
        { id: "sv-meteo2", titre: "Comment prédire la météo ?", source: "C'est pas sorcier", type: "video", lien: "https://www.youtube.com/watch?v=RjWvJCDPW1I", etiquette: "consolider", duree: "26 min", note: "Le bulletin météo, c'est le document 2 de l'activité sur Lisa et le tournoi de tennis." },
        { id: "sv-climat", titre: "Le climat : son histoire et ses changements", source: "C'est pas sorcier", type: "video", lien: "https://www.youtube.com/watch?v=lShBAXMb2yU", etiquette: "plusloin", duree: "26 min" }
      ],
      quiz: [
        { q: "« Demain, il pleuvra sur Paris. » C'est…", options: ["de la météo", "du climat"], bonne: 0, explication: "Une prévision à court terme, sur une zone limitée : c'est de la météorologie.", point: "Trier météo et climat", revoir: "sv-meteo1", fixe: true },
        { q: "« En moyenne, il fait plus chaud en été qu'en hiver à Paris. » C'est…", options: ["de la météo", "du climat"], bonne: 1, explication: "Une moyenne calculée sur de nombreuses années : c'est du climat.", point: "Trier météo et climat", revoir: "sv-climat", fixe: true },
        { q: "« Cette semaine, des matchs du tournoi de tennis ont été reportés à cause de la pluie. » C'est…", options: ["de la météo", "du climat"], bonne: 0, explication: "Un épisode de quelques jours : c'est un événement météorologique.", point: "Trier météo et climat", revoir: "sv-meteo2", fixe: true },
        { q: "« Le Sahara reçoit très peu de pluie, année après année. » C'est…", options: ["de la météo", "du climat"], bonne: 1, explication: "Ce qui se répète en moyenne sur des années décrit le climat.", point: "Trier météo et climat", revoir: "sv-climat", fixe: true },
        { q: "« Un orage violent a éclaté hier soir. » C'est…", options: ["de la météo", "du climat"], bonne: 0, explication: "Un phénomène ponctuel, à court terme : c'est de la météo.", point: "Trier météo et climat", revoir: "sv-meteo1", fixe: true },
        { q: "La climatologie étudie…", options: ["les valeurs moyennes des températures et des précipitations sur de nombreuses années", "le temps qu'il fera demain", "les tremblements de terre"], bonne: 0, explication: "Ces moyennes sont établies grâce à des mesures régulières pendant des années.", point: "Définir climat et météo", revoir: "sv-climat" },
        { q: "La météorologie étudie…", options: ["les phénomènes à court terme sur une zone limitée", "les moyennes sur des centaines d'années", "l'histoire de la Terre"], bonne: 0, explication: "Précipitations, température, vent : la météo prévoit les jours qui viennent.", point: "Définir climat et météo", revoir: "sv-meteo2" },
        { q: "Sur combien d'années calcule-t-on un climat de référence ?", options: ["30 ans", "1 an", "1 mois"], bonne: 0, explication: "La période de référence est de 30 ans.", point: "Définir climat et météo", revoir: "sv-climat" },
        { q: "1 mm de précipitations correspond à…", options: ["1 litre d'eau par mètre carré", "1 goutte par mètre carré", "1 seau d'eau par mètre carré"], bonne: 0, explication: "C'est la définition donnée dans le document 1.", point: "Les précipitations" },
        { q: "Un mois de mai très pluvieux prouve-t-il que le climat se dérègle ?", options: ["Non, c'est un événement météorologique", "Oui, forcément"], bonne: 0, explication: "Pour parler de climat, il faut comparer des moyennes sur de nombreuses années, pas un seul mois.", point: "Trier météo et climat", revoir: "sv-meteo2" },
        { q: "Pourquoi existe-t-il plusieurs zones climatiques sur Terre ?", options: ["Parce que le rayonnement du Soleil est inégalement réparti", "Parce que certains pays sont plus près du Soleil", "Parce que les océans chauffent l'air"], bonne: 0, explication: "Près de l'équateur, les rayons arrivent presque droits ; près des pôles, ils arrivent inclinés et se répartissent sur une plus grande surface.", point: "Les zones climatiques", revoir: "sv-climat" },
        { q: "Quel est le mot exact pour l'étude des moyennes sur une longue durée ?", options: ["la climatologie", "la météorologie", "la géologie"], bonne: 0, explication: "Climatologie : conditions moyennes (températures, précipitations) sur une région donnée, pendant plusieurs décennies.", point: "Le lexique du chapitre", revoir: "sv-climat", fixe: true },
        { q: "Et pour l'étude du temps à court terme, sur une zone limitée ?", options: ["la météorologie", "la climatologie", "l'astronomie"], bonne: 0, explication: "C'est la définition du lexique, mot pour mot.", point: "Le lexique du chapitre", revoir: "sv-meteo1", fixe: true },
        { q: "Combien y a-t-il de grandes zones climatiques sur Terre ?", options: ["Trois", "Deux", "Cinq"], bonne: 0, explication: "Trois : la zone chaude, la zone tempérée et la zone froide, qu'on appelle aussi polaire.", point: "Les zones climatiques", revoir: "sv-climat", fixe: true },
        { q: "Comment ces trois zones sont-elles disposées ?", options: ["De part et d'autre de l'équateur", "Du nord au sud, en bandes verticales", "Au hasard"], bonne: 0, explication: "La carte du document 1 le montre : la zone chaude autour de l'équateur, puis les zones tempérées, puis les zones froides vers les pôles.", point: "Les zones climatiques", revoir: "sv-climat" },
        { q: "Qu'est-ce qui explique l'existence de ces zones ?", options: ["L'inégale répartition de l'énergie solaire à la surface de la Terre", "La distance entre chaque pays et le Soleil", "La profondeur des océans"], bonne: 0, explication: "C'est ce que démontre le modèle expérimental : l'énergie solaire est plus concentrée à l'équateur qu'aux pôles.", point: "Les zones climatiques", revoir: "sv-climat", fixe: true },
        { q: "En zone tempérée, les relevés donnent 9,7 °C et 767 mm par an. En climat équatorial…", options: ["23,8 °C et 1617 mm par an", "5 °C et 200 mm par an", "les mêmes valeurs"], bonne: 0, explication: "Températures et précipitations sont bien plus élevées en zone chaude : ce sont les chiffres des graphiques de l'activité.", point: "Lire les graphiques", revoir: "sv-climat" },
        { q: "Sur quelles deux mesures repose la définition d'un climat ?", options: ["Les températures et les précipitations", "Le vent et les nuages", "L'humidité et la pression"], bonne: 0, explication: "Températures et précipitations moyennes, sur une longue période et une grande zone.", point: "Le lexique du chapitre", fixe: true },
        { q: "Le grand-père de Lisa pense qu'il va pleuvoir parce qu'il a plu l'an dernier. A-t-il raison ?", options: ["Non : un épisode de pluie ne dit rien de l'année suivante", "Oui : la pluie revient toujours à la même date"], bonne: 0, explication: "C'est la conclusion de l'activité : on ne déduit rien d'un seul phénomène météorologique.", point: "Le raisonnement de l'activité", revoir: "sv-meteo2", fixe: true },
        { q: "Le graphique du document 4 montre que les précipitations…", options: ["varient d'une année à l'autre, parfois au-dessus des normales, parfois en dessous", "augmentent chaque année sans exception", "sont identiques tous les ans"], bonne: 0, explication: "Plus fortes en 2007 et 2013, plus faibles en 2011 et 2015 : cette variation est normale.", point: "Le raisonnement de l'activité", revoir: "sv-meteo2" },
        { q: "Quand peut-on parler d'un dérèglement climatique ?", options: ["Quand un phénomène se répète sur plusieurs zones et sur plusieurs années", "Dès qu'un mois est plus pluvieux que d'habitude", "Quand un orage est très violent"], bonne: 0, explication: "C'est la phrase de conclusion du cours : un seul phénomène ne suffit jamais.", point: "Le raisonnement de l'activité", revoir: "sv-climat", fixe: true },
        { q: "Quelques jours de pluie à Paris en juin 2017, c'est…", options: ["un phénomène météorologique", "une preuve de dérèglement climatique"], bonne: 0, explication: "Le document 3 sert justement à montrer le piège : quelques jours ne relèvent pas de la climatologie.", point: "Trier météo et climat", revoir: "sv-meteo2" },
        { q: "Le climat se définit sur…", options: ["une grande surface et une longue période", "une petite zone et quelques jours", "une ville et une saison"], bonne: 0, explication: "C'est l'opposition centrale du chapitre : grande surface et longue durée pour le climat, petite zone et court terme pour la météo.", point: "Définir climat et météo", fixe: true },
        { q: "Où fait-il en moyenne le plus chaud ?", options: ["Près de l'équateur", "Près des pôles"], bonne: 0, explication: "C'est là que le Soleil chauffe le plus, car ses rayons y sont concentrés sur une petite surface.", point: "Les zones climatiques", revoir: "sv-climat" }
      ]
    },
    {
      id: "sv-courants",
      titre: "Les origines du climat : les courants atmosphériques",
      resume: "Pourquoi l'air bouge, et comment les vents transportent la chaleur. Chapitre en cours.",
      savaisTu: [
        "Une montgolfière vole grâce à une seule règle : l'air chaud monte, parce qu'il est plus léger que l'air froid qui l'entoure.",
        "Quand on ouvre la porte d'un four, l'air chaud file vers le plafond et l'air froid rase le sol : c'est un courant atmosphérique en miniature.",
        "Sans les vents, l'équateur serait encore plus brûlant et les pôles encore plus glacés. L'air en mouvement redistribue la chaleur du Soleil sur toute la planète.",
        "La pression de l'air se mesure avec un baromètre, en hectopascals. Autour de 1013 hPa, c'est la pression normale au niveau de la mer."
      ],
      supports: [
        { id: "sv-masses-air", titre: "Anticyclone et dépression : le mouvement des masses d'air", source: "C'est pas sorcier, extrait (apps.education)", type: "video", lien: "https://tube-sciences-technologies.apps.education.fr/w/9EpejRcFHxo9oqrLoLHJQn", etiquette: "decouvrir", note: "Un extrait court, préparé pour les élèves de 5e.", noteParent: "Plateforme de l'Éducation nationale (apps.education), extrait de C'est pas sorcier monté pour la 5e. C'est la première vidéo apps.education de l'application : si elle refuse de se lancer, signalez-le." },
        { id: "sv-vent-meteo", titre: "D'où vient le vent ? (Météo, l'émission complète)", source: "C'est pas sorcier", type: "video", lienDe: "sv-meteo1", etiquette: "consolider", noteParent: "Même épisode que dans le chapitre précédent : le lien est repris automatiquement." }
      ],
      quiz: [
        { q: "Que fait l'air chaud par rapport à l'air froid ?", options: ["Il monte", "Il descend", "Il reste immobile"], bonne: 0, explication: "C'est ce qui fait voler une montgolfière : l'air chaud monte.", point: "L'air chaud monte", revoir: "sv-masses-air" },
        { q: "Pourquoi l'air chaud monte-t-il ?", options: ["Parce qu'il est plus léger que l'air froid", "Parce que le vent le pousse", "Parce qu'il est attiré par le Soleil"], bonne: 0, explication: "Chauffé, l'air se dilate et devient moins dense : il s'élève au-dessus de l'air froid.", point: "L'air chaud monte" },
        { q: "Et l'air froid ?", options: ["Il descend, car il est plus lourd", "Il monte encore plus vite", "Il disparaît"], bonne: 0, explication: "L'air froid, plus dense, descend et prend la place de l'air chaud qui s'élève.", point: "L'air chaud monte" },
        { q: "Qu'est-ce qu'un vent ?", options: ["Un déplacement d'une masse d'air", "Un nuage qui avance", "De l'eau qui s'évapore"], bonne: 0, explication: "Le vent, c'est de l'air qui se déplace d'une zone à une autre.", point: "Les vents", revoir: "sv-masses-air" },
        { q: "Un anticyclone, c'est une zone de…", options: ["hautes pressions", "basses pressions", "pluie permanente"], bonne: 0, explication: "Anticyclone : pression élevée. Dépression : pression basse.", point: "Anticyclone et dépression", revoir: "sv-masses-air" },
        { q: "Une dépression, c'est une zone de…", options: ["basses pressions", "hautes pressions", "vent nul"], bonne: 0, explication: "Le mot le dit : la pression y est plus basse qu'ailleurs.", point: "Anticyclone et dépression", revoir: "sv-masses-air" },
        { q: "Dans quel sens souffle le vent ?", options: ["Des hautes pressions vers les basses pressions", "Des basses pressions vers les hautes pressions", "Toujours du nord vers le sud"], bonne: 0, explication: "L'air se déplace de l'anticyclone vers la dépression, comme de l'air qui s'échappe d'un ballon trop gonflé.", point: "Anticyclone et dépression", revoir: "sv-masses-air" },
        { q: "Quel temps un anticyclone apporte-t-il le plus souvent ?", options: ["Du beau temps", "De la pluie et des nuages", "De la neige à coup sûr"], bonne: 0, explication: "Quand la météo annonce un anticyclone, c'est en général le beau temps.", point: "Anticyclone et dépression" },
        { q: "Et une dépression ?", options: ["Des nuages et de la pluie", "Un grand soleil", "Aucun changement"], bonne: 0, explication: "Dans une dépression, l'air monte, se refroidit, et l'eau qu'il contient forme des nuages.", point: "Anticyclone et dépression" },
        { q: "À l'équateur, l'air très chauffé par le Soleil…", options: ["monte en altitude", "descend vers le sol", "reste sur place"], bonne: 0, explication: "C'est le point de départ des grands courants atmosphériques.", point: "Les courants à l'échelle de la Terre" },
        { q: "Quel est le rôle des courants atmosphériques pour le climat ?", options: ["Ils transportent la chaleur de l'équateur vers les pôles", "Ils refroidissent l'équateur jusqu'à le geler", "Ils n'ont aucun effet"], bonne: 0, explication: "Ils redistribuent l'énergie du Soleil, inégalement reçue selon la latitude.", point: "Les courants à l'échelle de la Terre" },
        { q: "Pourquoi l'air se met-il en mouvement à l'échelle de la planète ?", options: ["Parce que l'énergie solaire est inégalement répartie : l'équateur chauffe plus que les pôles", "Parce que la Terre est ronde, sans autre raison", "Parce que les océans le poussent"], bonne: 0, explication: "C'est le lien avec la première partie du chapitre : l'inégale répartition de l'énergie solaire crée des différences de température, donc des mouvements d'air.", point: "Les courants à l'échelle de la Terre" },
        { q: "Avec quel instrument mesure-t-on la pression atmosphérique ?", options: ["Un baromètre", "Un thermomètre", "Un pluviomètre"], bonne: 0, explication: "Thermomètre pour la température, pluviomètre pour la pluie, baromètre pour la pression.", point: "Mesurer l'atmosphère" },
        { q: "Les courants atmosphériques peuvent-ils modifier le climat d'une région ?", options: ["Oui", "Non"], bonne: 0, explication: "Un vent venu de l'océan ou du désert change la température et l'humidité d'une région.", point: "Les courants à l'échelle de la Terre" }
      ]
    }
  ]
});
